name: Pre-Release

on: [ push ]

permissions:
  contents: read

jobs:
  lib-release:
    name: pyroscope-main
    permissions:
      contents: write
    if: "startsWith(github.ref, 'refs/tags/lib-')"
    continue-on-error: true
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ github.ref_name }}
      release_name: "pyroscope-${{ github.ref_name }}"
      draft: true
      prerelease: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  clibuilder-release:
    name: clibuilder-release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: "startsWith(github.ref, 'refs/tags/clibuilder-')"
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker buildx create --use
      - run: make -C docker push_cli_builder
  manylinux-release:
    name: manylinux-release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: "startsWith(github.ref, 'refs/tags/manylinux-')"
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker buildx create --use
      - run: make -C docker push_aarch64 push_x86_64

  cli-release:
    name: pyroscope-cli
    permissions:
      contents: write
    if: "startsWith(github.ref, 'refs/tags/cli-')"
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ github.ref_name }}
      release_name: "pyroscope-${{ github.ref_name }}"
      draft: true
      prerelease: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  cli-artifacts:
    name: pyroscope-cli - build aritifacts
    needs: cli-release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
          submodules: recursive
      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: DOCKER_EXTRA="--push" make cli/docker-image
      - run: DOCKER_EXTRA="--output=." make cli/docker-image

      - name: Upload release archive
        uses: korniltsev/actions-upload-release-asset@a7f1a48a96ff80f206fd26bdbfcf81539d44fa5e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.cli-release.outputs.upload_url }}
          asset_path: "./pyroscope-cli"
          asset_name: "pyroscope-cli"
          asset_content_type: application/octet-stream

  pprofrs-release:
    name: pyroscope-pprofrs
    permissions:
      contents: write
    if: "startsWith(github.ref, 'refs/tags/pprofrs-')"
    continue-on-error: true
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ github.ref_name }}
      release_name: "Backend: ${{ github.ref_name }}"
      draft: true
      prerelease: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  rbspy-release:
    name: pyroscope-rbspy
    permissions:
      contents: write
    if: "startsWith(github.ref, 'refs/tags/rbspy-')"
    continue-on-error: true
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ github.ref_name }}
      release_name: "Backend: ${{ github.ref_name }}"
      draft: true
      prerelease: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  pyspy-release:
    name: pyroscope-pyspy
    permissions:
      contents: write
    if: "startsWith(github.ref, 'refs/tags/pyspy-')"
    continue-on-error: true
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ github.ref_name }}
      release_name: "Backend: ${{ github.ref_name }}"
      draft: true
      prerelease: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  python-release:
    name: Python Package
    permissions:
      contents: write
    if: "startsWith(github.ref, 'refs/tags/python-')"
    continue-on-error: true
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ github.ref_name }}
      release_name: "Python Package: ${{ github.ref_name }}"
      draft: true
      prerelease: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  python-release-linux:
    needs: [ 'python-release' ]
    name: Release python linux amd64
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: AutoModality/action-clean@492b2d2e2e77247bfd0b17eaa89a371b2f3430ee # v1
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - run: make wheel/linux/amd64
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: ${{ github.sha }}
          path: pyroscope_ffi/python/dist/*

      - name: Upload release artifact
        uses: korniltsev/actions-upload-release-asset@a7f1a48a96ff80f206fd26bdbfcf81539d44fa5e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.python-release.outputs.upload_url }}
          asset_path: "pyroscope_ffi/python/dist/pyroscope*.whl"
  python-release-linux-arm:
    needs: [ 'python-release' ]
    name: Release python linux arm64
    runs-on: [self-hosted, Linux, ARM64]
    permissions:
      contents: write

    steps:
      - uses: AutoModality/action-clean@492b2d2e2e77247bfd0b17eaa89a371b2f3430ee # v1
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - run: make wheel/linux/arm64
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: ${{ github.sha }}
          path: pyroscope_ffi/python/dist/*

      - name: Upload release artifact
        uses: korniltsev/actions-upload-release-asset@a7f1a48a96ff80f206fd26bdbfcf81539d44fa5e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.python-release.outputs.upload_url }}
          asset_path: "pyroscope_ffi/python/dist/pyroscope*.whl"
  python-release-macos:
    needs: [ 'python-release' ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - macos-version: "11.0"
            target: x86_64-apple-darwin
            py-platform: macosx-11_0_x86_64
            mk-arch: amd64
          - macos-version: "11.0"
            target: aarch64-apple-darwin
            py-platform: macosx-11_0_arm64
            mk-arch: arm64

    name: macOS - ${{ matrix.py-platform }}
    runs-on: macos-${{ matrix.macos-version }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: 1.76.0
          targets: ${{ matrix.target }}

      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: 3.11

      - run: make pyroscope_ffi/clean wheel/mac/${{ matrix.mk-arch }}

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: ${{ github.sha }}
          path: pyroscope_ffi/python/dist/*

      - name: Upload release artifact
        uses: korniltsev/actions-upload-release-asset@a7f1a48a96ff80f206fd26bdbfcf81539d44fa5e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.python-release.outputs.upload_url }}
          asset_path: "pyroscope_ffi/python/dist/pyroscope*.whl"
  python-release-sdist:
    needs: [ 'python-release' ]
    name: sdist
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: AutoModality/action-clean@492b2d2e2e77247bfd0b17eaa89a371b2f3430ee # v1
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false

      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip pipenv wheel
      - name: Build sdist
        run: python setup.py sdist
        working-directory: pyroscope_ffi/python

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: ${{ github.sha }}
          path: pyroscope_ffi/python/dist/*

      - name: Upload release artifact
        uses: korniltsev/actions-upload-release-asset@a7f1a48a96ff80f206fd26bdbfcf81539d44fa5e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.python-release.outputs.upload_url }}
          asset_path: "pyroscope_ffi/python/dist/pyroscope-io-*.tar.gz"

  ruby-release:
    name: Ruby Gem
    permissions:
      contents: write
    if: "startsWith(github.ref, 'refs/tags/ruby-')"
    continue-on-error: true
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ github.ref_name }}
      release_name: "Ruby Gem: ${{ github.ref_name }}"
      draft: true
      prerelease: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  ruby-release-linux:
    needs: [ 'ruby-release' ]
    name: Release Linux gem amd64
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: AutoModality/action-clean@492b2d2e2e77247bfd0b17eaa89a371b2f3430ee # v1
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - run: make gem/linux/amd64
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: ${{ github.sha }}
          path: pyroscope_ffi/ruby/pkg/*.gem

      - name: Upload release artifact
        uses: korniltsev/actions-upload-release-asset@a7f1a48a96ff80f206fd26bdbfcf81539d44fa5e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.ruby-release.outputs.upload_url }}
          asset_path: "pyroscope_ffi/ruby/pkg/*.gem"

  ruby-release-linux-arm:
    needs: [ 'ruby-release' ]
    name: Release Linux gem arm64
    runs-on: [ self-hosted, Linux, ARM64 ]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - run: make gem/linux/arm64
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: ${{ github.sha }}
          path: pyroscope_ffi/ruby/pkg/*.gem

      - name: Upload release artifact
        uses: korniltsev/actions-upload-release-asset@a7f1a48a96ff80f206fd26bdbfcf81539d44fa5e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.ruby-release.outputs.upload_url }}
          asset_path: "pyroscope_ffi/ruby/pkg/*.gem"

  ruby-release-macos:
    needs: [ 'ruby-release' ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - macos-version: "11.0"
            target: x86_64-apple-darwin
            mk-arch: amd64
          - macos-version: "11.0"
            target: aarch64-apple-darwin
            mk-arch: arm64

    name: macOS - ${{ matrix.target }}
    runs-on: macos-${{ matrix.macos-version }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@e5517072e87f198d9533967ae13d97c11b604005 # v1.99.0
        with:
          ruby-version: '3.1'
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: 1.76.0
          targets: ${{ matrix.target }}

      - run: make pyroscope_ffi/clean gem/mac/${{ matrix.mk-arch }}

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: ${{ github.sha }}
          path: pyroscope_ffi/ruby/pkg/*.gem

      - name: Upload release artifact
        uses: korniltsev/actions-upload-release-asset@a7f1a48a96ff80f206fd26bdbfcf81539d44fa5e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.ruby-release.outputs.upload_url }}
          asset_path: "pyroscope_ffi/ruby/pkg/*.gem"

  ruby-release-source:
    needs: [ 'ruby-release' ]
    name: source
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: AutoModality/action-clean@492b2d2e2e77247bfd0b17eaa89a371b2f3430ee # v1
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@e5517072e87f198d9533967ae13d97c11b604005 # v1.99.0
        with:
          ruby-version: '3.1'

      - name: Install bundles
        run: bundle
        working-directory: pyroscope_ffi/ruby

      - name: Build source gem
        run: rake source:gem
        working-directory: pyroscope_ffi/ruby

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: ${{ github.sha }}
          path: pyroscope_ffi/ruby/pkg/*.gem

      - name: Upload release artifact
        uses: korniltsev/actions-upload-release-asset@a7f1a48a96ff80f206fd26bdbfcf81539d44fa5e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.ruby-release.outputs.upload_url }}
          asset_path: "pyroscope_ffi/ruby/pkg/*.gem"
